### ISSUE TITLE
Filter games to those that are unplayed in collection

### ISSUE THREAD

**Issue by boardgamemeeple** [gameshelf/gameshelf.github.io#24]

**Comment by junqdu** [comment]
I don't know about this, since you could just sort by # of plays
<img width="1580" alt="screen shot 2018-01-18 at 10 57 43 pm" src="https://user-images.githubusercontent.com/4250728/35138398-2b33f356-fca3-11e7-8c37-47e2fb797497.png">

**Comment by boardgamemeeple** [comment]
Hi. What I would like to be able to do is sort by plays and then be able to do a 2nd sort based on BGG / weight etc to try and work through my list of many unplayed games. 
There was a long post about unplayed Games recently in a FB group and I was pleased I wasn’t the only one with the problem but need to find a way to focus on it. 

Sent from my iPhone

On 19 Jan 2018, at 06:59, Jun Du <notifications@github.com> wrote:

I don't know about this, since you could just sort by # of plays

**Comment by junqdu** [comment]
@boardgamemeeple implemented, check it out

**Comment by boardgamemeeple** [comment]
Awesome work! So many enhancements. Love this site!

You should put up a donation link for people to recognise your hard work!

Sent from my iPad

On 19 Jan 2018, at 09:03, Jun Du <notifications@github.com> wrote:

@boardgamemeeple implemented, check it out

**Comment by boardgamemeeple** [comment]
Hi. Also the “filter by mechanisms” doesn’t seem to work on my iPhone or iPad. I click on it but nothing happens... bug?

Thanks
Gareth 

Sent from my iPhone

On 19 Jan 2018, at 09:03, Jun Du <notifications@github.com> wrote:

Closed #24.

**Comment by junqdu** [comment]
@boardgamemeeple You have to give me more detail for me to debug, like whats your bgg id? What did you click on.

**Comment by boardgamemeeple** [comment]
Open page in safart on imac or iphone or ipad.

Click on the button called “filter by mechanisms” and nothing happens. What’s it supposed to do?

 

VJBeam is bgg user.

**Comment by junqdu** [comment]
@boardgamemeeple You are suppose to see a list of checkboxes, I guess I need to fix this bug for Safari.
<img width="902" alt="screen shot 2018-01-19 at 10 34 06 am" src="https://user-images.githubusercontent.com/4250728/35165748-53788636-fd04-11e7-8bdd-4df57ae23c5b.png">

**Comment by boardgamemeeple** [comment]
Ok, nothing happens on any ios device ive used. Great idea though ☺

**Comment by junqdu** [comment]
@boardgamemeeple bug is fixed for Safari now, and donation link has added under help page, thanks for you suggestions.

**Comment by boardgamemeeple** [comment]
Morning. 
Still buggy. It now shows the tick boxes and I can select tick boxes but can’t then make box window close apart from clicking the cancel button so it doesn’t allow me to filter and see the results. Make sense?

Sent from my iPhone

On 19 Jan 2018, at 19:10, Jun Du <notifications@github.com> wrote:

@boardgamemeeple bug is fixed for Safari now, and donation link has added under help page, thanks for you suggestions.
